//////////////////////////////////////////////////////////////////////////////////////
// This file is distributed under the University of Illinois/NCSA Open Source License.
// See LICENSE file in top directory for details.
//
// Copyright (c) 2018 Jeongnim Kim and QMCPACK developers.
//
// File developed by: Mark Dewing, mdewing@anl.gov, Argonne National Laboratory
//
// File created by: Mark Dewing, mdewing@anl.gov, Argonne National Laboratory
//////////////////////////////////////////////////////////////////////////////////////
#include <catch2/catch_test_macros.hpp>
#include "Utilities/for_testing/Catch2Approx.h"

#include "OhmmsSoA/VectorSoaContainer.h"
#include "spline2/MultiBspline.hpp"
#include "spline2/MultiBsplineOffloadMapper.hpp"
#include "spline2/MultiBsplineEval.hpp"
#include "spline2/MultiBsplineVGLH_OMPoffload.hpp"
#include "QMCWaveFunctions/BsplineFactory/contraction_helper.hpp"
#include "config/stdlib/Constants.h"
#include "OMPTarget/OffloadAlignedAllocators.hpp"
#include "OMPTarget/OMPTargetMath.hpp"
#include "einspline/bspline_create.h"
#if defined(ENABLE_OFFLOAD)
#include <omp.h>
#endif

namespace qmcplusplus
{

TEST_CASE("SymTrace", "[spline2]")
{
  // Code from here to the end of the function generate by gen_trace.py

  double h00 = 1;
  double h01 = 2;
  double h02 = 3;
  double h11 = 4.4;
  double h12 = 1.1;
  double h22 = 0.9;

  double gg[6] = {0.1, 1.6, 1.2, 2.3, 9.4, 2.3};

  double tr = SymTrace(h00, h01, h02, h11, h12, h22, gg);
  CHECK(tr == Approx(29.43));
}


template<typename T>
void test_prefactors()
{
  T a[4];
  T da[4];
  T d2a[4];
  T tx;

  // Code from here to the end the of function generated by gen_prefactor.py

  tx = 0.1;
  spline2::MultiBsplineData<T>::compute_prefactors(a, tx);
  CHECK(a[0] == Approx(0.1215));
  CHECK(a[1] == Approx(0.657167));
  CHECK(a[2] == Approx(0.221167));
  CHECK(a[3] == Approx(0.000166667));

  tx = 0.8;
  spline2::MultiBsplineData<T>::compute_prefactors(a, da, d2a, tx);
  CHECK(a[0] == Approx(0.00133333));
  CHECK(da[0] == Approx(-0.02));
  CHECK(d2a[0] == Approx(0.2));
  CHECK(a[1] == Approx(0.282667));
  CHECK(da[1] == Approx(-0.64));
  CHECK(d2a[1] == Approx(0.4));
  CHECK(a[2] == Approx(0.630667));
  CHECK(da[2] == Approx(0.34));
  CHECK(d2a[2] == Approx(-1.4));
  CHECK(a[3] == Approx(0.0853333));
  CHECK(da[3] == Approx(0.32));
  CHECK(d2a[3] == Approx(0.8));
}

TEST_CASE("double prefactors", "[spline2]") { test_prefactors<double>(); }

TEST_CASE("float prefactors", "[spline2]") { test_prefactors<float>(); }

/** Supports testing many sizes of splines for benchmarking
 *  modified from einspline/tests/test_3d.cpp
 */

template<typename T, int GRID_SIZE, int NUM_SPLINES>
struct test_splines_base
{
  const int num_splines = NUM_SPLINES;
  int npad;
  BCtype_d bc[3];
  Ugrid grid[3];

  int N = GRID_SIZE;
  double delta;
  std::vector<double> data;

  test_splines_base()
  {
    data.resize(N * N * N);
    npad = getAlignedSize<T>(num_splines);

    grid[0].start = 0.0;
    grid[0].end   = 1.0;
    grid[0].num   = N;

    grid[1].start = 0.0;
    grid[1].end   = 1.0;
    grid[1].num   = N;

    grid[2].start = 0.0;
    grid[2].end   = 1.0;
    grid[2].num   = N;

    delta = (grid[0].end - grid[0].start) / grid[0].num;

    bc[0].lCode = PERIODIC;
    bc[0].rCode = PERIODIC;
    bc[0].lVal  = 0.0;
    bc[0].rVal  = 0.0;
    bc[1].lCode = PERIODIC;
    bc[1].rCode = PERIODIC;
    bc[1].lVal  = 0.0;
    bc[1].rVal  = 0.0;
    bc[2].lCode = PERIODIC;
    bc[2].rCode = PERIODIC;
    bc[2].lVal  = 0.0;
    bc[2].rVal  = 0.0;

    double tpi = 2 * M_PI;
    // Generate the data in double precision regardless of the target spline precision
    for (int i = 0; i < N; i++)
      for (int j = 0; j < N; j++)
        for (int k = 0; k < N; k++)
        {
          double x                    = delta * i;
          double y                    = delta * j;
          double z                    = delta * k;
          data[i * N * N + j * N + k] = std::sin(tpi * x) + std::sin(3 * tpi * y) + std::sin(4 * tpi * z);
        }
  }
};

/** Unspecialized test_splines doesn't test eval values
 */
template<typename T, int GRID_SIZE = 5, int NUM_SPLINES = 1>
struct test_splines : public test_splines_base<T, GRID_SIZE, NUM_SPLINES>
{
  using base = test_splines_base<T, GRID_SIZE, NUM_SPLINES>;
  using base::bc;
  using base::data;
  using base::delta;
  using base::grid;
  using base::N;
  using base::npad;
  using base::num_splines;

  test_splines() : test_splines_base<T, GRID_SIZE, NUM_SPLINES>() {};

  void test()
  {
    MultiBspline<T> bs(grid, bc, npad);

    REQUIRE(bs.num_splines() == npad);

    UBspline_3d_d* aspline = create_UBspline_3d_d(grid[0], grid[1], grid[2], bc[0], bc[1], bc[2], data.data());

    for (int i = 0; i < num_splines; i++)
      bs.set_spline(*aspline, i);

    destroy_Bspline(aspline);

    //  The values for N=5 are not good enough for finer grids so by default we don't do those checks

    TinyVector<T, 3> pos = {0, 0, 0};

    aligned_vector<T> v(npad);
    spline2::evaluate3d(bs.getSplinePtr(), pos, v);

    VectorSoaContainer<T, 3> dv(npad);
    VectorSoaContainer<T, 6> hess(npad);
    spline2::evaluate3d_vgh(bs.getSplinePtr(), pos, v, dv, hess);

    pos = {0.1, 0.2, 0.3};
    spline2::evaluate3d(bs.getSplinePtr(), pos, v);

    spline2::evaluate3d_vgh(bs.getSplinePtr(), pos, v, dv, hess);

    VectorSoaContainer<T, 3> lap(npad);
    spline2::evaluate3d_vgl(bs.getSplinePtr(), pos, v, dv, lap);

    VectorSoaContainer<T, 10> ghess(npad);
    spline2::evaluate3d_vghgh(bs.getSplinePtr(), pos, v, dv, hess, ghess);
  }
};

template<typename T>
void test_mapped_vgl_contraction()
{
  constexpr int num_splines = 513;
  test_splines_base<T, 5, num_splines> setup;
  MultiBspline<T> bs(setup.grid, setup.bc, setup.npad);
  bs.flush_zero();

  std::vector<double> mixed_data(setup.data.size());
  const double tpi = 2 * M_PI;
  for (int i = 0; i < setup.N; ++i)
    for (int j = 0; j < setup.N; ++j)
      for (int k = 0; k < setup.N; ++k)
      {
        const double x = setup.delta * i;
        const double y = setup.delta * j;
        const double z = setup.delta * k;
        mixed_data[i * setup.N * setup.N + j * setup.N + k] =
            std::sin(tpi * (x + y)) + 2.0 * std::cos(tpi * (y + z)) + 3.0 * std::sin(tpi * (z + x));
      }

  UBspline_3d_d* aspline = create_UBspline_3d_d(setup.grid[0], setup.grid[1], setup.grid[2], setup.bc[0], setup.bc[1],
                                                setup.bc[2], mixed_data.data());
  REQUIRE(aspline != nullptr);
  for (int i = 0; i < num_splines; ++i)
    bs.set_spline(*aspline, i);
  destroy_Bspline(aspline);

  auto* host_spline = bs.getSplinePtr();
  REQUIRE(host_spline->coefs_size % setup.npad == 0);
  for (size_t offset = 0; offset < host_spline->coefs_size; offset += setup.npad)
    for (int index = 0; index < num_splines; ++index)
      host_spline->coefs[offset + index] *= T(index + 1);

  MultiBsplineOffloadMapper<T> mapped_bs(bs);
  mapped_bs.mapToDevice();
  mapped_bs.updateToDevice();

  // A non-diagonal reciprocal lattice produces all six independent metric terms.
  const T reciprocal_lattice[9] = {T(1.0), T(0.2), T(-0.1), T(0.05), T(0.9), T(0.3), T(-0.2), T(0.1), T(1.1)};
  Vector<T, OffloadAllocator<T>> GGt(9);
  for (int row = 0; row < 3; ++row)
    for (int col = 0; col < 3; ++col)
    {
      T product = T();
      for (int k = 0; k < 3; ++k)
        product += reciprocal_lattice[row * 3 + k] * reciprocal_lattice[col * 3 + k];
      GGt[row * 3 + col] = product;
    }
  GGt.updateTo();

  const size_t field_stride = setup.npad;
  Vector<T, OffloadAllocator<T>> vgh_output(field_stride * SoAFields3D::NUM_FIELDS);
  constexpr T canary = T(-12345.5);
  Vector<T, OffloadAllocator<T>> vgl_output(field_stride * SoAFields3D::NUM_FIELDS, canary);
  vgl_output.updateTo();

  const auto* spline_ptr   = bs.getSplinePtr();
  const auto* spline_coefs = spline_ptr->coefs;
  auto* GGt_ptr            = GGt.data();
  auto* vgh_output_ptr     = vgh_output.data();
  auto* vgl_output_ptr     = vgl_output.data();

  constexpr size_t ChunkSizePerTeam = 512;
  const size_t NumTeams             = (field_stride + ChunkSizePerTeam - 1) / ChunkSizePerTeam;
  int initial_device                = 0;
  PRAGMA_OFFLOAD("omp target teams distribute num_teams(NumTeams) map(from: initial_device)")
  for (size_t team_id = 0; team_id < NumTeams; ++team_id)
  {
#if defined(ENABLE_OFFLOAD)
    if (team_id == 0)
      initial_device = omp_is_initial_device();
#endif
    const size_t first = ChunkSizePerTeam * team_id;
    const size_t last  = omptarget::min(first + ChunkSizePerTeam, field_stride);
    int ix, iy, iz;
    T a[4], b[4], c[4], da[4], db[4], dc[4], d2a[4], d2b[4], d2c[4];
    spline2::computeLocationAndFractional(spline_ptr, T(0.137), T(0.293), T(0.419), ix, iy, iz, a, b, c, da, db, dc,
                                          d2a, d2b, d2c);
    const T symGGt[6] = {GGt_ptr[0], GGt_ptr[1] + GGt_ptr[3], GGt_ptr[2] + GGt_ptr[6],
                         GGt_ptr[4], GGt_ptr[5] + GGt_ptr[7], GGt_ptr[8]};

    PRAGMA_OFFLOAD("omp parallel for")
    for (size_t index = first; index < last; ++index)
    {
      spline2offload::evaluate_vgh_impl_v2(spline_ptr, spline_coefs, ix, iy, iz, static_cast<int>(index), a, b, c, da,
                                           db, dc, d2a, d2b, d2c, vgh_output_ptr + index, field_stride);
      vgh_output_ptr[field_stride * SoAFields3D::LAPL + index] =
          SymTrace(vgh_output_ptr[field_stride * SoAFields3D::HESS00 + index],
                   vgh_output_ptr[field_stride * SoAFields3D::HESS01 + index],
                   vgh_output_ptr[field_stride * SoAFields3D::HESS02 + index],
                   vgh_output_ptr[field_stride * SoAFields3D::HESS11 + index],
                   vgh_output_ptr[field_stride * SoAFields3D::HESS12 + index],
                   vgh_output_ptr[field_stride * SoAFields3D::HESS22 + index], symGGt);

      spline2offload::evaluate_vgl_impl_v2(spline_ptr, spline_coefs, ix, iy, iz, static_cast<int>(index), a, b, c, da,
                                           db, dc, d2a, d2b, d2c, symGGt, vgl_output_ptr + index, field_stride,
                                           field_stride * SoAFields3D::LAPL);
    }
  }

  vgh_output.updateFrom();
  vgl_output.updateFrom();

#if defined(ENABLE_OFFLOAD)
  CHECK(initial_device == 0);
#endif
  CHECK(std::abs(vgh_output[field_stride * SoAFields3D::HESS01]) > T(1));
  CHECK(std::abs(vgh_output[field_stride * SoAFields3D::HESS02]) > T(1));
  CHECK(std::abs(vgh_output[field_stride * SoAFields3D::HESS12]) > T(1));

  const int compared_fields[] = {SoAFields3D::VAL, SoAFields3D::GRAD0, SoAFields3D::GRAD1, SoAFields3D::GRAD2,
                                 SoAFields3D::LAPL};
  for (int index = 0; index < num_splines; ++index)
    for (const int field : compared_fields)
      CHECK(vgl_output[field_stride * field + index] == Approx(vgh_output[field_stride * field + index]));

  const int untouched_fields[] = {SoAFields3D::HESS00, SoAFields3D::HESS01, SoAFields3D::HESS02,
                                  SoAFields3D::HESS11, SoAFields3D::HESS12, SoAFields3D::HESS22};
  for (const int field : untouched_fields)
    for (int index = 0; index < num_splines; ++index)
      CHECK(vgl_output[field_stride * field + index] == canary);

  const T base_value = vgh_output[field_stride * SoAFields3D::VAL];
  CHECK(vgh_output[field_stride * SoAFields3D::VAL + 511] ==
        Approx(base_value * T(512)).epsilon(512 * std::numeric_limits<T>::epsilon()));
  CHECK(vgh_output[field_stride * SoAFields3D::VAL + 512] ==
        Approx(base_value * T(513)).epsilon(512 * std::numeric_limits<T>::epsilon()));
}

TEST_CASE("MultiBspline mapped VGL contraction double", "[spline2]") { test_mapped_vgl_contraction<double>(); }

TEST_CASE("MultiBspline mapped VGL contraction float", "[spline2]") { test_mapped_vgl_contraction<float>(); }

/** Partially specialized test_splines does test eval values
 * See gen_bspline_values.py
 */
template<typename T>
struct test_splines<T, 5, 1> : public test_splines_base<T, 5, 1>
{
  using base = test_splines_base<T, 5, 1>;
  using base::bc;
  using base::data;
  using base::delta;
  using base::grid;
  using base::N;
  using base::npad;
  using base::num_splines;

  test_splines() : test_splines_base<T, 5, 1>() {};

  void test()
  {
    MultiBspline<T> bs(grid, bc, npad);

    REQUIRE(bs.num_splines() == npad);

    UBspline_3d_d* aspline = create_UBspline_3d_d(grid[0], grid[1], grid[2], bc[0], bc[1], bc[2], data.data());

    for (int i = 0; i < num_splines; i++)
      bs.set_spline(*aspline, i);

    destroy_Bspline(aspline);

    //  Code from here to the end of the function is generated by gen_bspline_values.py

    TinyVector<T, 3> pos = {0, 0, 0};

    // symbolic value at pos =  (cx[0]/6 + 2*cx[1]/3 + cx[2]/6)*(cy[0]/6 + 2*cy[1]/3 + cy[2]/6)*(cz[0]/6 + 2*cz[1]/3 + cz[2]/6)

    aligned_vector<T> v(npad);
    spline2::evaluate3d(bs.getSplinePtr(), pos, v);
    CHECK(v[0] == Approx(-3.529930688e-12));

    VectorSoaContainer<T, 3> dv(npad);
    VectorSoaContainer<T, 6> hess(npad);
    spline2::evaluate3d_vgh(bs.getSplinePtr(), pos, v, dv, hess);
    // Gradient
    CHECK(dv[0][0] == Approx(6.178320809));
    CHECK(dv[0][1] == Approx(-7.402942564));
    CHECK(dv[0][2] == Approx(-6.178320809));

    // Hessian
    for (int i = 0; i < 6; i++)
    {
      CHECK(hess[0][i] == Approx(0.0));
    }

    pos = {0.1, 0.2, 0.3};
    spline2::evaluate3d(bs.getSplinePtr(), pos, v);

    // Value
    CHECK(v[0] == Approx(-0.9476393279));

    spline2::evaluate3d_vgh(bs.getSplinePtr(), pos, v, dv, hess);
    // Value
    CHECK(v[0] == Approx(-0.9476393279));
    // Gradient
    CHECK(dv[0][0] == Approx(5.111042137));
    CHECK(dv[0][1] == Approx(5.989106342));
    CHECK(dv[0][2] == Approx(1.952244379));
    // Hessian
    CHECK(hess[0][0] == Approx(-21.34557341));
    CHECK(hess[0][1] == Approx(1.174505743e-09));
    CHECK(hess[0][2] == Approx(-1.1483271e-09));
    CHECK(hess[0][3] == Approx(133.9204891));
    CHECK(hess[0][4] == Approx(-2.15319293e-09));
    CHECK(hess[0][5] == Approx(34.53786329));


    VectorSoaContainer<T, 3> lap(npad);
    spline2::evaluate3d_vgl(bs.getSplinePtr(), pos, v, dv, lap);
    // Value
    CHECK(v[0] == Approx(-0.9476393279));
    // Gradient
    CHECK(dv[0][0] == Approx(5.111042137));
    CHECK(dv[0][1] == Approx(5.989106342));
    CHECK(dv[0][2] == Approx(1.952244379));
    // Laplacian
    CHECK(lap[0][0] == Approx(147.1127789));

    VectorSoaContainer<T, 10> ghess(npad);
    spline2::evaluate3d_vghgh(bs.getSplinePtr(), pos, v, dv, hess, ghess);
    // Value
    CHECK(v[0] == Approx(-0.9476393279));
    // Gradient
    CHECK(dv[0][0] == Approx(5.111042137));
    CHECK(dv[0][1] == Approx(5.989106342));
    CHECK(dv[0][2] == Approx(1.952244379));
    // Hessian
    CHECK(hess[0][0] == Approx(-21.34557341));
    CHECK(hess[0][1] == Approx(1.174505743e-09));
    CHECK(hess[0][2] == Approx(-1.1483271e-09));
    CHECK(hess[0][3] == Approx(133.9204891));
    CHECK(hess[0][4] == Approx(-2.15319293e-09));
    CHECK(hess[0][5] == Approx(34.53786329));


    // Catch default is 100*(float epsilson)
    double eps = 2000 * std::numeric_limits<float>::epsilon();

    // Gradient of Hessian
    CHECK(ghess[0][0] == Approx(-213.455734));
    CHECK(ghess[0][1] == Approx(2.311193459e-09).epsilon(eps));
    CHECK(ghess[0][2] == Approx(3.468205279e-09).epsilon(eps));
    CHECK(ghess[0][3] == Approx(1.58092329e-07).epsilon(eps));
    CHECK(ghess[0][4] == Approx(1.255694171e-08).epsilon(eps));
    CHECK(ghess[0][5] == Approx(4.78981157e-08).epsilon(eps));
    CHECK(ghess[0][6] == Approx(-1753.041961));
    CHECK(ghess[0][7] == Approx(-2.575826885e-09).epsilon(eps));
    CHECK(ghess[0][8] == Approx(-4.683496702e-09).epsilon(eps));
    CHECK(ghess[0][9] == Approx(-81.53283531));

    MultiBsplineOffloadMapper<T> mapped_bs(bs);
    mapped_bs.mapToDevice();
    mapped_bs.updateToDevice();

    const int num_pos = 3;
    Vector<T, OffloadAllocator<T>> pos_arr{0.1, 0.2, 0.3, 0.3, 0.1, 0.2, 0.1, 0.2, 0.3};
    pos_arr.updateTo();

    auto num_splines_padded = bs.num_splines_padded();

    Vector<T, OffloadAllocator<T>> spline_v_vals(num_pos * num_splines_padded);
    mapped_bs.mw_evaluate_v(num_pos, pos_arr.data(), spline_v_vals.data(), num_splines_padded);
    spline_v_vals.updateFrom();

    CHECK(spline_v_vals[0] == Approx(-0.9476393279));
    CHECK(spline_v_vals[num_splines_padded * 2] == Approx(-0.9476393279));

    Vector<T, OffloadAllocator<T>> spline_vgh_vals(num_pos * num_splines_padded * SoAFields3D::NUM_FIELDS);
    mapped_bs.mw_evaluate_vgh(num_pos, pos_arr.data(), spline_vgh_vals.data(),
                              num_splines_padded * SoAFields3D::NUM_FIELDS, num_splines_padded);
    spline_vgh_vals.updateFrom();

    CHECK(spline_vgh_vals[0] == Approx(-0.9476393279));
    CHECK(spline_vgh_vals[num_splines_padded * SoAFields3D::GRAD1] == Approx(5.989106342));
    CHECK(spline_vgh_vals[num_splines_padded * SoAFields3D::HESS22] == Approx(34.53786329));

    Vector<T, OffloadAllocator<T>>
        spline_vgh_vals_w2(spline_vgh_vals, &spline_vgh_vals[num_splines_padded * SoAFields3D::NUM_FIELDS * 2],
                           num_splines_padded * SoAFields3D::NUM_FIELDS);
    CHECK(spline_vgh_vals_w2[0] == Approx(-0.9476393279));
    CHECK(spline_vgh_vals_w2[num_splines_padded * SoAFields3D::GRAD1] == Approx(5.989106342));
    CHECK(spline_vgh_vals_w2[num_splines_padded * SoAFields3D::HESS22] == Approx(34.53786329));
  }
};

TEST_CASE("MultiBspline periodic double", "[spline2]") { test_splines<double>().test(); }

/** Purpose is to evaluate performance
 *  this seems to be the largest spline mesh in the examples
 *  the '#pragma omp parallel for's in BslpineAllocator are worth about 
 *  a 16% speedup here on 32 threads vs serial
 *  for a 500x500x500 grid the speed up is a factor of 2
 *
 *  This test is only run if you explicitly call the .spline2 tag.
 */
TEST_CASE("MultiBspline periodic double large", "[.spline2]")
{
  test_splines<double, 128, 10> test;
  for (int i = 0; i < 20; i++)
    test.test();
}

TEST_CASE("MultiBspline periodic float", "[spline2]") { test_splines<float>().test(); }

} // namespace qmcplusplus
